# -*- coding: utf-8 -*-
"""gptbased분류모델

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1WQS15o7I8Js-s-7MXAqSWj1Cr6hjIwgD
"""

import openai
from enum import Enum
from typing import Dict, Tuple

# OpenAI API 키 설정
openai.api_key = "your-api-key-here"

class ConversationType(Enum):
    """대화 유형 분류"""
    WORKPLACE_HARASSMENT = "직장 내 괴롭힘"
    EXTORTION = "갈취"
    OTHER_HARASSMENT = "기타 괴롭힘"
    THREATS = "협박"
    NORMAL = "일반 대화"

def classify_conversation(text: str) -> Tuple[ConversationType, float, str]:
    """
    GPT를 사용하여 대화를 분류합니다.

    Args:
        text: 분류할 대화 텍스트

    Returns:
        (분류 유형, 신뢰도, 설명)
    """

    system_prompt = """당신은 대화 내용을 분석하여 다음 5가지 유형으로 분류하는 전문가입니다:

1. '직장 내 괴롭힘': 직장 내에서 발생하는 따돌림, 명예훼손, 업무 방해, 부당한 대우
   - 예: "너 이 일은 못 해", "넌 여기 안 맞아", "계속 실수하니까 너만 남아서 일해"

2. '갈취': 금전이나 물품을 불법적으로 요구하는 행위
   - 예: "이번에 돈 좀 빌려줘야 해", "회식비는 네가 다 내", "봉급의 일부를 줘야 해"

3. '기타 괴롭힘': 개인정보 노출, 외모 비난, 사생활 침해 등
   - 예: "너 프라이빗한 정보 알았어", "외모가 그렇게 못생겼어", "너의 개인사항 공개하겠다"

4. '협박': 명시적 또는 암묵적 위협, 신체적/정신적 해를 끼치겠다는 위협
   - 예: "가만 있지 말고", "이따 주차장에서 봐", "이 얘기 누구한테 말하면 큰일 난다"

5. '일반 대화': 위의 4가지에 해당하지 않는 일반적인 대화

분석 시 다음을 고려하세요:
- 맥락과 의도
- 언어의 톤과 강도
- 권력 관계의 암시
- 반복성 여부
- 상대방에게 미치는 영향

응답 형식:
{
  "classification": "분류 유형명",
  "confidence": 0.0~1.0 사이의 신뢰도,
  "reasoning": "분류 이유 설명",
  "risk_level": "낮음/중간/높음"
}"""

    try:
        response = openai.ChatCompletion.create(
            model="gpt-4",
            messages=[
                {"role": "system", "content": system_prompt},
                {"role": "user", "content": f"다음 대화를 분류해주세요:\n\n{text}"}
            ],
            temperature=0.3,
            max_tokens=500
        )

        result = response.choices[0].message.content

        # 응답 파싱
        import json
        parsed = json.loads(result)

        classification_type = ConversationType[parsed["classification"].upper().replace(" ", "_")]
        confidence = parsed["confidence"]
        reasoning = parsed["reasoning"]

        return classification_type, confidence, reasoning

    except Exception as e:
        print(f"오류 발생: {e}")
        return ConversationType.NORMAL, 0.0, "분류 실패"

def batch_classify(conversations: list) -> list:
    """
    여러 대화를 한 번에 분류합니다.

    Args:
        conversations: 분류할 대화 리스트

    Returns:
        분류 결과 리스트
    """
    results = []

    for i, conversation in enumerate(conversations, 1):
        print(f"[{i}/{len(conversations)}] 분석 중...")
        classification_type, confidence, reasoning = classify_conversation(conversation)

        result = {
            "conversation": conversation,
            "type": classification_type.value,
            "confidence": confidence,
            "reasoning": reasoning
        }
        results.append(result)

    return results

def generate_report(results: list) -> str:
    """
    분류 결과 리포트를 생성합니다.
    """
    report = "=== 직장 괴롭힘 대화 분류 리포트 ===\n\n"

    # 유형별 집계
    type_counts = {}
    for result in results:
        conv_type = result["type"]
        type_counts[conv_type] = type_counts.get(conv_type, 0) + 1

    report += "[ 분류 결과 ]\n"
    for conv_type, count in sorted(type_counts.items()):
        percentage = (count / len(results)) * 100
        report += f"- {conv_type}: {count}건 ({percentage:.1f}%)\n"

    report += "\n[ 위험도가 높은 대화 ]\n"
    high_risk = [r for r in results if r["confidence"] > 0.8]

    for i, result in enumerate(high_risk, 1):
        report += f"\n{i}. {result['type']}\n"
        report += f"   신뢰도: {result['confidence']:.0%}\n"
        report += f"   사유: {result['reasoning']}\n"

    return report

# 사용 예제
if __name__ == "__main__":
    # 테스트 대화들
    test_conversations = [
        "안녕, 오늘 날씨 좋네. 점심 먹을래?",
        "너 요즘 계속 실수만 하네. 다른 팀으로 가는 게 낫지 않을까?",
        "이번 달 회식비는 너가 다 내. 알겠지?",
        "너 개인정보 알고 있어. 조심해.",
        "그 프로젝트 어떻게 진행되고 있어?",
    ]

    print("직장 내 괴롭힘 대화 분류 시작...\n")
    results = batch_classify(test_conversations)

    # 결과 출력
    for i, result in enumerate(results, 1):
        print(f"\n[대화 {i}]")
        print(f"분류: {result['type']}")
        print(f"신뢰도: {result['confidence']:.0%}")
        print(f"설명: {result['reasoning']}")

    # 리포트 생성
    report = generate_report(results)
    print("\n" + report)